-- Generated by nwg-displays on 2026-06-27 at 15:35:39. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@65.0",
    position = "1920x0",
    scale = 1.0
})
